
coverage:
  status:
    project:
      default:
        target: auto  # target is increasing coverage
        threshold: 0.2%
        informational: false
    patch:
      default:
        informational: true  # otherwise this falses way too much
    
